C2DEVEL-9643: add create_default_vpc method
C2Devel/boto pull request #124
Opened 2021-04-09 11:34 UTC by kirill-ilichev

2021-04-16 08:24 UTC, pkulev requested changes

2021-04-16 08:24 UTC, pkulev commented on boto/vpc/__init__.py
> +        params = dict()
Use dict literal, just `{}`.

2021-04-24 13:35 UTC, pkulev approved these changes

2021-06-15 08:58 UTC, Sharpeye90 commented
@kirill-ilichev rebase pls

2021-06-15 10:02 UTC, merged